function [data, auxData, metaData, txtData, weights] = mydata_Linepithema_humile
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Arthropoda';
metaData.class      = 'Insecta';
metaData.order      = 'Hymenoptera';
metaData.family     = 'Formicidae';
metaData.species    = 'Linepithema_humile';
metaData.species_en = 'Argentine ant';

metaData.ecoCode.climate = {'Am','Aw','Cfa','Cfb','Csa','Csb'};
metaData.ecoCode.ecozone = {'T'};
metaData.ecoCode.habitat = {'0iTh','0iThf','0iTf','0iTi','0iTs','0iTg','0iTd'};
metaData.ecoCode.embryo  = {'Tntf','Thw'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biO','biHn','biHe','biCi','biS','biSi','biSva','biSvr','biSvb','biSvm'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(28); % K, body temp

metaData.data_0     = {'ab','ab','tj','te','am','Ww0','Wwj','Wwi','Wwe','Wdi','Wde','Lb','Lj','Le','Ri'};
metaData.data_1     = {'WwR','Tab','Ttj', 'Tte'};

metaData.COMPLETE   = 1.5; % using criteria of LikaKear2011

metaData.author     = {'Filipe Chichorro'};
metaData.date_subm  = [2021 5 19];
metaData.email      = {'filipechichorro@gmail.com'};
metaData.address    = {'Finnish Museum of Natural History'};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight.augustine@akvaplan.niva.no'};
metaData.date_acc   = [2021 5 18];

%% set zero-variate data
data.ab = 16; units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = {'Abri2010'};
  temp.ab = C2K(28); units.temp.ab = 'K'; label.temp.ab = 'temperature';
  comment.ab = 'measured on workers';
data.tj = 45; units.tj = 'd'; label.tj = 'time since birth at end acceleration'; bibkey.tj = {'Abri2010'};
  temp.tj = C2K(28); units.temp.tj = 'K'; label.temp.tj = 'temperature';
  comment.tj = 'measured on workers';
data.te = 9; units.te = 'd'; label.te = 'time since pupation at emergence'; bibkey.te = {'Abri2010'};
  temp.te = C2K(28); units.temp.te = 'K'; label.temp.te = 'temperature';
  comment.te = 'measured on workers';
data.am = 1461; units.am = 'd'; label.am = 'life span'; bibkey.am = {'guess'};
  temp.am = C2K(28); units.temp.am = 'K'; label.temp.am = 'temperature';
  comment.am = 'The lifespan of L humile is unknown because 90% of them are executed by their workers every year. However, Ant queens are known to last for several years, hence the 4 year lifespan chosen.';

data.Ww0 = 2e-05; units.Ww0 = 'g'; label.Ww0 = 'initial wet weight'; bibkey.Ww0 = {'AnDi'};
data.Wwe = 0.00277; units.Wwe = 'g'; label.Wwe = 'wet weight of imago'; bibkey.Wwe = {'KellPass1988'};
  comment.Wwe = 'measured from emerged gyne';
data.Wde = 0.00068; units.Wde = 'g'; label.Wde = 'dry weight of imago'; bibkey.Wde = {'KellPass1988'};
  comment.Wde = 'measured from emerged gyne';

data.Lb = 0.03; units.Lb = 'cm'; label.Lb = 'length at birth'; bibkey.Lb = {'AnDi'};
data.Lj = 0.44; units.Lj = 'cm'; label.Lj = 'length at end acceleration'; bibkey.Lj = {'WheeWhee1989'};
  comment.Lj = 'length through spiracles';
data.Le = 0.475; units.Le = 'cm'; label.Le = 'length of imago'; bibkey.Le = {'AnDi'};
  comment.Le = '4.5 to 5mm. Reported as 4.5 to 5.0 cm in AnimalDiversity, which is obviously a typo';

%data.Ri = 20; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = {'Kell1988'};
%  temp.Ri = C2K(28); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
%  comment.Ri = '28ºC is the optimal oviposition temperature (Abril2008)';

%% set uni-variate data
% wet weight - reproduction rate
data.WwR = [ ... 
  0.0042 19
  0.0044 16
  0.0037 13
  0.005 6
  0.0042 3
  0.0041 3
  0.004 2
  0.0041 0
  0.0036 0
  0.0034 0
  0.0035 1
  0.0032 2
  0.0036 4
  0.0032 5];
units.WwR = {'g', '#/d'}; label.WwR = {'wet weight', 'reproduction rate'};
temp.WwR = C2K(28); units.temp.WwR = 'K'; label.temp.WwR = 'temperature';
bibkey.WwR = {'Kell1988'};
comment.WwR = 'measured on artificial colonies with one queen (Fig 1). The study also presents results from polygyne colonies, which are what we typically see in nature. I chose monogyne because it better reflects optimal conditions through the queens perspective.';

% Temperature - age at birth
%data.Tab = [ ... 
%  18 57.7
%  21 31.8
%  24 20.3
%  26 17.8
%  28 16
%  30 15.7];
%units.Tab = {'T', 'd'}; label.Tab= {'Temperature', 'age at birth'};
%bibkey.Tab = {'Abri2010'};
%comment.Tab = 'Incubation times measured on eggs belonging to the worker caste (best information available)';

% Temperature - time since birth at end acceleration
%data.Ttj = [ ... 
%  21 103.8
%  24 64.9
%  26 85.3
%  28 43
%  30 37.5];
%units.Ttj = {'T', 'd'}; label.Ttj= {'Temperature', 'time since birth at end acceleration'};
%bibkey.Ttj = {'Abri2010'};
%comment.Ttj = 'Incubation times measured on eggs belonging to the worker caste (best information available)';

% Temperature - time since pupation at emergence
%data.Tte = [ ... 
%  21 25.6
%  24 16.2
%  26 11.4
%  28 9
%  30 8];
%units.Tte = {'T', 'd'}; label.Tte= {'Temperature', 'time since pupation at emergence'};
%bibkey.Tte = {'Abri2010'};
%comment.Tte = 'Incubation times measured on eggs belonging to the worker caste (best information available)';

%% set weights for all real data
weights = setweights(data, []);
%weights.ab = 5 * weights.ab;
%weights.tj = 5 * weights.tj;
%weights.te = 5 * weights.te;
%weights.am = 5 * weights.am;

weights.Ww0 = 5 * weights.Ww0;
%weights.Tab = 0.1 * weights.Tab;
%weights.Ttj = 0.1 * weights.Ttj;
%weights.Tte = 0.1 * weights.Tte;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Discussion points
D1  = 'The ovoposition rate does not vary much with age in this species';
D2  = 'The duration of the juvenile stages is of the worker caste, since no studies were found for queens. However, early estimates (NeweBarb1913) indicate that their periods should not differ greatly between workers, males and queens.';
metaData.bibkey.D2 = 'NeweBarb1913';
D3  = 'Aron2001 measured the dry and wet weight of these species under high and low protein content, thus the relationship between both variables can be estimated from there';
metaData.bibkey.D3 = 'Aron2001';
D4  = 'Boom1995 has some data on energetics of this species, such as energy from fat, ADWM.';
metaData.bibkey.D4 = 'Boom1995';
metaData.discussion = struct('D1',D1, 'D2',D2, 'D3',D3, 'D4',D4);

%% Facts
F1  = 'draft fact';
metaData.bibkey.F1 = 'F1';
metaData.facts = struct('F1',F1);

%% Acknowledgment
metaData.acknowledgment = 'draft acknowledgment';

%% Links
metaData.links.id_CoL = '3V2M8'; % Cat of Life
metaData.links.id_EoL = '473775'; % Ency of Life
metaData.links.id_Wiki = 'Linepithema humile'; % Wikipedia
metaData.links.id_ADW = 'Linepithema humile'; % Anim Div. Web
metaData.links.id_Taxo = '201047'; % Taxonomicon
metaData.links.id_WoRMS = 'some number (replace)';

%% References
bibkey = 'Abri2010'; type = 'article'; bib = [ ...
'author = {Sílvia Abril and Jordi Oliveras and Crisanto Gómez}, ' ... 
'title = {Effect of temperature on the development and survival of the Argentine ant, Linepithema humile}, ' ... 
'journal = {Journal of Insect Science}, ' ... 
'year = {2010}, ' ... 
'volume = {10}, ' ... 
'doi = {10.1673/031.010.9701}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'AnDi'; type = 'misc'; bib = [ ...
'author = {Angela Miner (author), Animal Diversity Web Staff, Leila Siciliano Martina (editor), Animal Diversity Web Staff}, ' ... 
'note = {retrieved in 20210519}, ' ... 
'howpublished = {\url{https://animaldiversity.org/accounts/Linepithema_humile/}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kell1988'; type = 'article'; bib = [ ...
'author = {Laurent Keller}, ' ... 
'title = {Pouvoir attractif des reines de la fourmi d''Argentine, Iridomyrmex humilis (Mayr). Rôle de la polygynie et du statut physiologique des reines}, ' ... 
'journal = {Bull. Soc. Vaudoise Sci. Nat}, ' ... 
'year = {1988}, ' ... 
'volume = {79}, ' ... 
'pages = {93-102}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'KellPass1988'; type = 'article'; bib = [ ...
'author = {Laurent Keller and Luc Passera}, ' ... 
'title = {Energy Investment in Gynes of the Argentine Ant Iridomyrmex humilis (Mayr) in Relation to the Mode of Colony Founding in Ants (Hymenoptera:Formicidae)}, ' ... 
'journal = {International Journal of Invertebrate Reproduction and Development}, ' ... 
'year = {1988}, ' ... 
'volume = {13}, ' ... 
'pages = {31-38}, ' ... 
'doi = {10.1080/01688170.1988.10510340}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'KellPass1990'; type = 'article'; bib = [ ...
'author = {Laurent Keller and Luc Passera}, ' ... 
'title = {Fecundity of ant queens in relation to their age and the mode of colony founding}, ' ... 
'journal = {Insectes Sociaux}, ' ... 
'year = {1990}, ' ... 
'volume = {37}, ' ... 
'pages = {116-130}, ' ... 
'doi = {10.1007/BF02224025}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'WheeWhee1989'; type = 'article'; bib = [ ...
'author = {George C Wheeler and Jeanette Wheeler}, ' ... 
'title = {Notes on Ant Larvae}, ' ... 
'journal = {Transactions of the American Entomological Society}, ' ... 
'year = {1989}, ' ... 
'volume = {115}, ' ... 
'pages = {457-473}, ' ... 
'howpublished = {\url{https://www.jstor.org/stable/25078504}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
