function [data, auxData, metaData, txtData, weights] = mydata_Linepithema_humile
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Arthropoda';
metaData.class      = 'Insecta';
metaData.order      = 'Hymenoptera';
metaData.family     = 'Formicidae';
metaData.species    = 'Linepithema_humile';
metaData.species_en = 'Argentine ant';

metaData.ecoCode.climate = {'Am','Aw','Cfa','Cfb','Csa','Csb'};
metaData.ecoCode.ecozone = {'T'};
metaData.ecoCode.habitat = {'0iTh','0iThf','0iTf','0iTi','0iTs','0iTg','0iTd'};
metaData.ecoCode.embryo  = {'Tntf','Thw'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biO','biHn','biHe','biCi','biS','biSi','biSva','biSvr','biSvb','biSvm'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(25); % K, body temp

metaData.data_0     = {'Lh','Le','Ri','te','Wwh','te','ah','am','Wde','Wwe','tp','Lj'};
metaData.data_1     = {};

metaData.COMPLETE   = 1; % using criteria of LikaKear2011

metaData.author     = {'Filipe Chichorro'};
metaData.date_subm  = [2021 5 17];
metaData.email      = {'filipechichorro@gmail.com'};
metaData.address    = {'Finnish Museum of Natural History'};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight.augustine@akvaplan.niva.no'};
metaData.date_acc   = [2021 5 17];

%% set zero-variate data
data.Lh = 0.03; units.Lh = 'cm'; label.Lh = 'length at hatch'; bibkey.Lh = {'NewelBarber1913'};
  comment.Lh = 'length of egg. width is 0.02cm. Newly hatched larvae length is 0.049cm';
data.Le = 0.475; units.Le = 'cm'; label.Le = 'length of imago'; bibkey.Le = {'AnimalDiversity'};
  comment.Le = '4.5-5mm (female queen)';

data.Ri = 60; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = {'AnimalDiversity'};
  temp.Ri = C2K(25); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = 'Temperature is a guess based on midrange of optimal temperature vals';

data.Wwh = 2e-05; units.Wwh = 'g'; label.Wwh = 'wet weight at hatch'; bibkey.Wwh = {'AnimalDiversity'};
  comment.Wwh = 'Mass of egg';

data.te = 21; units.te = 'd'; label.te = 'time since pupation at emergence'; bibkey.te = {'AnimalDiversity'};
  temp.te = C2K(25); units.temp.te = 'K'; label.temp.te = 'temperature';
  comment.te = 'temperature guess';
data.ah = 28; units.ah = 'd'; label.ah = 'age at hatch'; bibkey.ah = {'NewelBarber1913'};
  temp.ah = C2K(25); units.temp.ah = 'K'; label.temp.ah = 'temperature';
  comment.ah = 'varies wildy with temperature, from 12-55 days';
data.am = 730; units.am = 'd'; label.am = 'life span'; bibkey.am = {'guess'};
  temp.am = C2K(25); units.temp.am = 'K'; label.temp.am = 'temperature';
  comment.am = '90% of queens of this species are executed each year, making it hard to estimate total lifespan. but queen ants often last for years, so I guessed around two years';

data.Wwe = 0.0036; units.Wwe = 'g'; label.Wwe = 'wet weight of imago'; bibkey.Wwe = {'AnimalDiversity'};
  comment.Wwe = '(queen)';

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Discussion points
D1  = 'Incubation period of eggs, larvae, pupae (not for queens) available at several temperatures';
metaData.bibkey.D1 = 'D1';
D2  = 'data for workers and males also available';
metaData.bibkey.D2 = 'D2';
metaData.discussion = struct('D1',D1, 'D2',D2);

%% Links
metaData.links.id_CoL = '3V2M8'; % Cat of Life
metaData.links.id_EoL = '473775'; % Ency of Life
metaData.links.id_Wiki = 'Linepithema humile'; % Wikipedia
metaData.links.id_ADW = 'Linepithema humile'; % Anim Div. Web
metaData.links.id_Taxo = '201047'; % Taxonomicon
metaData.links.id_WoRMS = 'some number (replace)';

%% References
bibkey = 'AnimalDiversity'; type = 'misc'; bib = [ ...
'howpublished = {\url{https://animaldiversity.org/accounts/Linepithema_humile/}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'NewelBarber1913'; type = 'article'; bib = [ ...
'author = {Wilmon Newel;TC Barber}, ' ... 
'title = {The Argentine Ant}, ' ... 
'journal = {Bureau of Entomology}, ' ... 
'year = {1913}, ' ... 
'volume = {122}, ' ... 
'pages = {1-98}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
